### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [brangray/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, it looks good. Your code is well organized and you used some good techniques. Take a look at the issues I created, they will help optimize some of your code. Here is an article with some good tips as well: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by brangray** [comment]
Great feedback! Thanks so much for reviewing. I was at an exhibit for work late last week and over the weekend so I got a bit behind.

Brandee
